# Generated by Django 5.1 on 2024-09-02 17:15

import django_ckeditor_5.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_content_alter_blog_created_at_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_link', models.URLField(blank=True, null=True)),
                ('meta', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_link', models.URLField(blank=True, null=True)),
                ('meta', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('category', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
