# Generated by Django 5.1 on 2024-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
        migrations.RemoveField(
            model_name='myresource',
            name='category',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='LikedIp',
        ),
        migrations.DeleteModel(
            name='MyResource',
        ),
    ]
